//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy.Endpoints.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy.Endpoints.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleAsync method should be async.
        /// </summary>
        internal static string AsyncHandlersForSyncEndpointDescription {
            get {
                return ResourceManager.GetString("AsyncHandlersForSyncEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleAsync method is not async, rename to Handle or make async.
        /// </summary>
        internal static string AsyncHandlersForSyncEndpointMessageFormat {
            get {
                return ResourceManager.GetString("AsyncHandlersForSyncEndpointMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandleAsync method is not async.
        /// </summary>
        internal static string AsyncHandlersForSyncEndpointTitle {
            get {
                return ResourceManager.GetString("AsyncHandlersForSyncEndpointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEndpoint should have a Handle or HandleAsync method.
        /// </summary>
        internal static string EmptyEndpointDescription {
            get {
                return ResourceManager.GetString("EmptyEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Implements IEndpoint, but does not have a method Handle or HandleAsync.
        /// </summary>
        internal static string EmptyEndpointMessageFormat {
            get {
                return ResourceManager.GetString("EmptyEndpointMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEndpoint does not have Handle Method.
        /// </summary>
        internal static string EmptyEndpointTitle {
            get {
                return ResourceManager.GetString("EmptyEndpointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEndpoint should have a single Handle or HandleAsync method.
        /// </summary>
        internal static string MultipleHandlersForEndpointDescription {
            get {
                return ResourceManager.GetString("MultipleHandlersForEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} public Handle or HandleAsync methods, only one is allowed for IEndpoint.
        /// </summary>
        internal static string MultipleHandlersForEndpointMessageFormat {
            get {
                return ResourceManager.GetString("MultipleHandlersForEndpointMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEndpoint has multiple Handle Methods.
        /// </summary>
        internal static string MultipleHandlersForEndpointTitle {
            get {
                return ResourceManager.GetString("MultipleHandlersForEndpointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle method should not be async.
        /// </summary>
        internal static string SyncHandlersForAsyncEndpointDescription {
            get {
                return ResourceManager.GetString("SyncHandlersForAsyncEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle method should not be async, rename to HandleAsync.
        /// </summary>
        internal static string SyncHandlersForAsyncEndpointMessageFormat {
            get {
                return ResourceManager.GetString("SyncHandlersForAsyncEndpointMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle method is async.
        /// </summary>
        internal static string SyncHandlersForAsyncEndpointTitle {
            get {
                return ResourceManager.GetString("SyncHandlersForAsyncEndpointTitle", resourceCulture);
            }
        }
    }
}
